services:
  front:
    build:
      context: ${PWD}
      dockerfile: ./dockerfiles/Dockerfile-gha
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://localhost:8080
    entrypoint: "./prod-entrypoint.sh"
