services:
  front:
    build:
      context: ${PWD}/dockerfiles/
      dockerfile: Dockerfile-local
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080
    entrypoint: "./dev-entrypoint.sh"
