services:
  front:
    build:
      context: ${PWD}
      dockerfile: ./dockerfiles/Dockerfile-local
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080
    tty: true
    stdin_open: true
    entrypoint: "./dev-entrypoint.sh"
