FROM node:22-alpine3.19

WORKDIR /app

COPY ../app/ /app/

# Install the dependencies
RUN npm install --only=production

# RUN npm install pm2 -g

RUN nuxt build

EXPOSE 3000

# CMD ["pm2-runtime", "start", "nuxt", "start"]
# CMD ["nuxt", "start"]