FROM node:22-alpine3.19

EXPOSE 3000

WORKDIR /app

COPY ../app/ /app/

RUN rm -rf ./node_modules && \
    rm -rf ./package-lock.json

RUN npm install pm2 -g

# Install the dependencies
RUN npm install --omit=dev

RUN npm run build


# CMD ["pm2-runtime", "start", "nuxt", "start"]
# CMD ["nuxt", "start"]