FROM node:22

# # Expose the port
EXPOSE 3000

# # Set the working directory
WORKDIR /app



# # Copy the app
COPY ../app/ /app/

# # Clean the environment and workspace
RUN rm -rf ./node_modules && \
    rm -rf ./package-lock.json && \
    rm -rf ./.nuxt && \
    rm -f /tmp/nitro/worker-*.sock

# # Install global dependencies
RUN npm install -g npm@latest

# # Install project dependencies and Playwright
RUN npm install && \
    npx playwright install-deps && \
    npm init playwright@latest -y && \
    npx playwright install --with-deps chromium && \
    npm run postinstall && \
    npm install -g playwright && \
    npm install -D @playwright/test

# Ensure Playwright is in the PATH
ENV PATH="/app/node_modules/.bin:${PATH}"

# Configure Playwright
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV PLAYWRIGHT_BROWSERS_PATH=/usr/lib/chromium

# # Par défaut, on ne met pas de CMD car on veut pouvoir exécuter différentes commandes