FROM node:22-alpine3.19

# # Expose the port
EXPOSE 3000

# # Set the working directory
WORKDIR /app

# # Copy the app
COPY ../app/ /app/

# # Clean the environment and workspace
RUN rm -rf ./node_modules && \
    rm -rf ./package-lock.json && \
    rm -rf ./.nuxt && \
    rm -f /tmp/nitro/worker-*.sock

# # Install global dependencies
RUN npm install -g npm@latest

# # Install project dependencies and Playwright
RUN npm install && \
    npm init playwright@latest -y && \
    npm run postinstall

# # Par défaut, on ne met pas de CMD car on veut pouvoir exécuter différentes commandes