FROM node:22-alpine3.19

# # Expose the port
EXPOSE 3000

# # Set the working directory
WORKDIR /app

# # Copy the app
COPY ../app/ /app/

# # Clean the environment and workspace
RUN rm -rf ./node_modules && \
    rm -rf ./package-lock.json && \
    rm -rf ./.nuxt && \
    rm -f /tmp/nitro/worker-*.sock

# # Install the dependencies
RUN npm install -g npm@latest pm2

# # Install the dependencies
RUN npm install

# # Run the postinstall
RUN npm run postinstall

# # Build the app
RUN npm run build

# # Run the app
CMD ["pm2-runtime", "start", "ecosystem.config.cjs"]