name: Auto Assign
on:
  workflow_run:
    # Le nom doit correspondre exactement au workflow précédent ("Proof HTML" ici)
    workflows: ["Proof HTML"]
    types: [completed]
jobs:
  run:
    # Exécuter seulement si le workflow "Proof HTML" s'est terminé avec succès
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: jehanvaire,T4rg3n,kiloutyg,RomainCrz
          numOfAssignee: 3
          abortIfPreviousAssignees: true 
          allowSelfAssign: true